services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: task-list_api 
    env_file:
      - ./.env
    
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres_db:
        condition: service_healthy


  postgres_db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"] # Deve aguardar o banco ficar operacional
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
